# Generated by Django 5.1.2 on 2024-12-14 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_comment_options_alter_post_caption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='posts_images/', verbose_name='Imagen'),
        ),
    ]
